### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'protoc': 'protoc'

### ISSUE THREAD

**Issue by zabir-nabil** [vadimkantorov/caffemodel2pytorch#17]
I'm getting the following error while converting to pytorch/keras.

```
Traceback (most recent call last):
  File "/home/vmuser/anaconda3/envs/torch_old/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/vmuser/anaconda3/envs/torch_old/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vmuser/Data/deblur/LP_deblur_cafee/caffemodel2pytorch/caffemodel2pytorch.py", line 386, in <module>
    net_param = initialize(args.caffe_proto).NetParameter()
  File "/home/vmuser/Data/deblur/LP_deblur_cafee/caffemodel2pytorch/caffemodel2pytorch.py", line 39, in initialize
    subprocess.check_call(['protoc', '--proto_path', os.path.dirname(local_caffe_proto), '--python_out', codegen_dir, local_caffe_proto])
  File "/home/vmuser/anaconda3/envs/torch_old/lib/python3.6/subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/vmuser/anaconda3/envs/torch_old/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/vmuser/anaconda3/envs/torch_old/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/vmuser/anaconda3/envs/torch_old/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'protoc': 'protoc'
```

**Comment by vadimkantorov** [comment]
You should install protobuf on your own and make `protoc` discoverable by Python (make sure it's in PATH)
