### ISSUE TITLE
how do i install it

### ISSUE THREAD

**Issue by leconghieu99** [vadimkantorov/caffemodel2pytorch#21]
I did it and got an error
import caffemodel2pytorch as caffe
caffe.set_mode_gpu()
caffe.set_device(0)

AttributeError                            Traceback (most recent call last)
[<ipython-input-24-1b139244a157>](https://localhost:8080/#) in <module>()
      1 get_ipython().magic('cd /content/caffemodel2pytorch')
      2 import caffemodel2pytorch as caffe
----> 3 caffe.set_mode_gpu()
      4 caffe.set_device(0)

AttributeError: module 'caffemodel2pytorch' has no attribute 'set_mode_gpu'

**Comment by leconghieu99** [comment]
Traceback (most recent call last):
  File "solve_fphb_crack.py", line 46, in <module>
    interp_layers = [k for k in solver.net.params.keys() if 'up' in k]
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'Net' object has no attribute 'params'
how to fix
